# -*- coding: utf-8 -*-
#
# FOG Project documentation build configuration file, created by
# sphinx-quickstart on Fri Apr 21 11:34:59 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))
# import pydata_sphinx_theme
import sphinx_rtd_theme

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autosectionlabel',
    'sphinx_panels'
]
# autosummary_generate = True
autosectionlabel_prefix_document = True
# panels_add_bootstrap_css = False
todo_include_todos = False
# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'FOG Project'
copyright = u'2020, FOG Project'
author = u'FOG Project'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'1.5.9'
# The full version, including alpha/beta/rc tags.
release = u'1.5.9'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.md']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
# todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'
# html_theme = 'pydata_sphinx_theme'
html_logo = "_static/img/logo/fog-logo.png"
html_favicon = "_static/img/logo/fog-logo.ico"

html_theme_options = {
    # Theme options for pydata_sphinx_theme
#     "external_links": [
#       {"name": "Forums", "url": "https://forums.fogproject.org"},
#       {"name": "Fogproject", "url": "https://fogproject.org"},
#       {"name": "Github Repos", "url": "https://github.com/FOGProject"}

#   ],
#     "github_url": "https://github.com/FOGProject/fog-docs",
#     "twitter_url": "https://twitter.com/FOGProject",
    # "use_edit_page_button": True,
    # "show_toc_level": 3,
    # "navigation_with_keys": True

    #config options for sphinx_rtd_theme
    'logo_only': False,
    'display_version': True,
    'style_external_links': True,
    # Toc Options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 6,
    'includehidden': True,
    'titles_only': False
}

#used with pydata_sphinx_theme
# html_context = {
    # "github_user": "FOGProject",
    # "github_repo": "fog-focs",
    # "github_version": "master",
    # "doc_path": "/",
# }



# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'FOGProjectdoc'

html_css_files = [
    'css/custom.css',
    # 'js/custom.js',
    # 'js/index.js',
    # 'css/_admonitions.scss',
    # 'css/_base.scss',
    # 'css/_navbar.scss',
    # 'css/_variables.scss',
    # 'css/index.scss'
]


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'FOGProject.tex', u'FOG Project Documentation',
     u'FOG Project', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'fogproject', u'FOG Project Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'FOGProject', u'FOG Project Documentation',
     author, 'FOGProject', 'An open source computer cloning & management system',
     'Miscellaneous'),
]



# # -- Auto-convert markdown pages to demo --------------------------------------
# import recommonmark
# from recommonmark.transform import AutoStructify


# def setup(app):
#     app.add_transform(AutoStructify)